// Dailymotion Player Embed v-0.0.3507-rc1
// This file is generated dynamically, do not host it yourself
// Statically hosting or caching this file will break your integration
'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(l,p,t){if(l==Array.prototype||l==Object.prototype)return l;l[p]=t.value;return l};
$jscomp.getGlobal=function(l){l=["object"==typeof globalThis&&globalThis,l,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var p=0;p<l.length;++p){var t=l[p];if(t&&t.Math==Math)return t}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(l,p){var t=$jscomp.propertyToPolyfillSymbol[p];if(null==t)return l[p];t=l[t];return void 0!==t?t:l[p]};$jscomp.polyfill=function(l,p,t,v){p&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(l,p,t,v):$jscomp.polyfillUnisolated(l,p,t,v))};
$jscomp.polyfillUnisolated=function(l,p,t,v){t=$jscomp.global;l=l.split(".");for(v=0;v<l.length-1;v++){var u=l[v];if(!(u in t))return;t=t[u]}l=l[l.length-1];v=t[l];p=p(v);p!=v&&null!=p&&$jscomp.defineProperty(t,l,{configurable:!0,writable:!0,value:p})};
$jscomp.polyfillIsolated=function(l,p,t,v){var u=l.split(".");l=1===u.length;v=u[0];v=!l&&v in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var L=0;L<u.length-1;L++){var F=u[L];if(!(F in v))return;v=v[F]}u=u[u.length-1];t=$jscomp.IS_SYMBOL_NATIVE&&"es6"===t?v[u]:null;p=p(t);null!=p&&(l?$jscomp.defineProperty($jscomp.polyfills,u,{configurable:!0,writable:!0,value:p}):p!==t&&(void 0===$jscomp.propertyToPolyfillSymbol[u]&&(t=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[u]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(u):$jscomp.POLYFILL_PREFIX+t+"$"+u),$jscomp.defineProperty(v,$jscomp.propertyToPolyfillSymbol[u],{configurable:!0,writable:!0,value:p})))};
$jscomp.polyfill("String.prototype.replaceAll",function(l){return l?l:function(p,t){if(p instanceof RegExp&&!p.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return p instanceof RegExp?this.replace(p,t):this.replace(new RegExp(String(p).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),t)}},"es_next","es3");
var _dmpesplayer=function(){function l(){return(new URL(window.location.href)).searchParams.get("dmLogger")||""}function p(a,b){if(Ea&&console[b]){for(var c=arguments.length,d=Array(2<c?c-2:0),f=2;f<c;f++)d[f-2]=arguments[f];c=[`%cPES%c${a}`,"border-radius: 0.125rem; padding: 0.0625rem 0.1875rem; margin: 0 0.0625rem; color: white;; background: purple","border-radius: 0.125rem; padding: 0.0625rem 0.1875rem; margin: 0 0.0625rem; color: white;; background: #ae27ae",...d];console[b](...c)}}function t(){let a=
null;if(I())return q.log("Skipping 3rd party cookie detection on dailymotion.com"),Promise.resolve();let b=new Promise(d=>{a=setTimeout(()=>{q.log("3rd party cookie","Received detection timeout");return d()},2E3)}),c=new Promise(d=>{if(I())return q.log("Skipping 3rd party cookie detection on dailymotion.com"),d();const f=document.createElement("script");f.src=`${ia()}/cookie.js`;f.onload=()=>{q.log("3rd party cookie","Script loaded");clearTimeout(a);return d()};f.onerror=()=>{q.log("3rd party cookie",
"Script error");clearTimeout(a);return d()};document.head.appendChild(f)});return Promise.race([c,b])}let v=a=>new Promise((b,c)=>{const d=a.getAttribute("load-status");if("loaded"===d)return b();if("error"===d)return c();a.addEventListener("load",()=>{a.setAttribute("load-status","loaded");b()});a.addEventListener("error",()=>{a.setAttribute("load-status","error");c()})}),u={"udger":{"browserOsFamily":"Linux","browserOsName":"Linux","browserUaFamily":"Chrome","browserUaName":"Chrome 122.0.0.0","browserUaVersion":122,"deviceType":"desktop"},"geoip":{"visitorAsNumber":"AS28573","visitorCity":"Araraquara","visitorContinent":"SA","visitorCountry":"BR","visitorRegion":"SP"},"playerEnv":"prod","playerGatekeepers":["PV5_ADSENSE_DISPLAY_PREROLL","PV5_AD_BUFFET","PV5_AD_COOKIE_SYNC","PV5_AUDIO_ADS_POC","PV5_COOKIE_SYNC_AB_TEST","PV5_DISABLE_AUDIO_VISUALIZER","PV5_ENABLE_IMA_OMSDK","PV5_IAS_INAPP","PV5_IAS_SAMPLING","PV5_IGNORE_EARLY_LOAD_MIDROLL","PV5_IMA_CUSTOM_PLAYBACK_IOS","PV5_IMA_NATIVE_POC","PV5_IMA_OVERLAY","PV5_IMA_REQUEST_TIMEOUT","PV5_LIVE_MIDROLL_DISABLED","PV5_MOAT_30","PV5_MULTI_FALLBACK","PV5_OEMBED_GEO","PV5_OMSDK","PV5_OMSDK_NATIVE","PV5_PROXY_LOAD_POSTROLL","PV5_SAVE_VAST_RECORD","PV5_TEMP_AD_SLOT_HEIGHT","PV5_TEMP_IMA_PAGEURL","PV5_TEMP_IMA_PAGEURL_OFFSITE","PV5_TEMP_VMAPNOJSONP","PV5_VERTICAL_ADS","PV5_WATCHTOWER","PV5_SIMID","PV5_MIDROLL_RETAKE_ONSITE","PV5_MIDROLL_RETAKE_OFFSITE","PV5_V2V_ONSITE_QUERY","PV5_ADS_ON_REPLAY_OFFSITE","PV5_IMA_COMPANION_AD","PV5_DISABLE_PUBLISHER_WITH_EMBEDDER"],"trafficSegment":586212,"v1st":"59259072-91dc-4ba2-aafb-840d434f7e17","player":{"id":"x7iwh","ownerId":"x1ypm1s","status":"ok","aspectRatio":"16:9","autoskipAfter":10,"autostart":"firstTimeViewable","color":"FF6A28","enableAdsAutopauseInactiveTab":false,"enableAdsControls":true,"enableAutomaticRecommendations":true,"enableAutonext":true,"enableAutoskip":false,"enableChannelLink":false,"enableClickToUnmute":true,"enableDmLogo":true,"enableGooglePolicyUi":false,"enableInfo":true,"enablePlaybackControls":true,"enableReceiveUrlLocation":false,"enableSharing":false,"enableSharingUrlLocation":false,"enableStartPipExpanded":false,"enableStartscreenDmLink":true,"enableTapToUnmute":true,"enableTitlesInVideoCards":true,"enableVideoTitleLink":false,"enableWaitForCustomConfig":false,"hasAds":true,"hasReachedPlaybackLimits":false,"pip":"on","recommendationsOptimisation":"monetization","watermarkImageType":"none","watermarkImageUrl":"","watermarkLinkType":"none","watermarkLinkUrl":""}},L=[{key:"id",isPublic:!0,isTrackable:!0},{key:"ownerId",isPublic:!1,isTrackable:!1},{key:"status",isPublic:!1,
isTrackable:!1},{key:"aspectRatio",isPublic:!0,isTrackable:!0},{key:"autoskipAfter",isPublic:!0,isTrackable:!0},{key:"autostart",isPublic:!0,isTrackable:!0},{key:"color",isPublic:!0,isTrackable:!0},{key:"enableAdsAutopauseInactiveTab",isPublic:!1,isTrackable:!0},{key:"enableAdsControls",isPublic:!0,isTrackable:!0},{key:"enableAutonext",isPublic:!0,isTrackable:!0},{key:"enableAutoskip",isPublic:!0,isTrackable:!0},{key:"enableChannelLink",isPublic:!0,isTrackable:!0},{key:"enableClickToUnmute",isPublic:!0,
isTrackable:!0},{key:"enableDmLogo",isPublic:!0,isTrackable:!0},{key:"enableGooglePolicyUi",isPublic:!0,isTrackable:!0},{key:"enableInfo",isPublic:!0,isTrackable:!0},{key:"enablePlaybackControls",isPublic:!0,isTrackable:!0},{key:"enableAutomaticRecommendations",isPublic:!0,isTrackable:!0},{key:"enableReceiveUrlLocation",isPublic:!0,isTrackable:!0},{key:"enableSharing",isPublic:!0,isTrackable:!0},{key:"enableSharingUrlLocation",isPublic:!0,isTrackable:!0},{key:"enableStartPipExpanded",isPublic:!0,
isTrackable:!0},{key:"enableStartscreenDmLink",isPublic:!0,isTrackable:!0},{key:"enableTapToUnmute",isPublic:!0,isTrackable:!0},{key:"enableTitlesInVideoCards",isPublic:!0,isTrackable:!0},{key:"enableVideoTitleLink",isPublic:!0,isTrackable:!0},{key:"enableWaitForCustomConfig",isPublic:!0,isTrackable:!0},{key:"hasAds",isPublic:!1,isTrackable:!0},{key:"hasReachedPlaybackLimits",isPublic:!1,isTrackable:!0},{key:"pip",isPublic:!0,isTrackable:!0},{key:"recommendationsOptimisation",isPublic:!0,isTrackable:!0},
{key:"watermarkImageType",isPublic:!0,isTrackable:!0},{key:"watermarkImageUrl",isPublic:!0,isTrackable:!1},{key:"watermarkLinkType",isPublic:!0,isTrackable:!0},{key:"watermarkLinkUrl",isPublic:!0,isTrackable:!1}],F=a=>{var b;return null===(b=u.playerGatekeepers)||void 0===b?void 0:b.includes(a)},Y=()=>{var a,b;return F("PV5_USE_GEO2_IFRAME")||(null===(a=window.dailymotion)||void 0===a?0:null===(b=a._do_not_use_8d7d83cd2395d780b51b)||void 0===b?0:b.isGeo2)?"https://geo2.dailymotion.com":"https://geo.dailymotion.com"},
ia=()=>{var a,b;return F("PV5_USE_GEO2_IFRAME")||(null===(a=window.dailymotion)||void 0===a?0:null===(b=a._do_not_use_8d7d83cd2395d780b51b)||void 0===b?0:b.isGeo2)?"https://geo2.dailymotion.com":"https://geo.dailymotion.com"},Z=(a,b)=>{const c={};L.filter(d=>d[b]).forEach(d=>{({key:d}=d);c[d]=a[d]});return c},Fa=function(a){let b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};b&&"object"===typeof b&&Object.keys(b).forEach(c=>{L.map(d=>{({key:d}=d);return d}).includes(c)&&I()&&(a[c]=b[c],
a.hasOverride=!0)});return a},ja=a=>"string"===typeof a?Ga(a):a,Ga=a=>{const b={};a.split("&").forEach(c=>{const [d,f]=c.split("=");d&&f&&(c=d.match(/([a-zA-Z0-9]+)\[([a-zA-Z0-9]+)\]/),"true"===f?b[d]=!0:"false"===f?b[d]=!1:f.match(/^[0-9]+$/)?b[d]=d.match(/color$/i)?f:parseInt(f):c?b[c[1]]={...b[c[1]],[c[2]]:decodeURIComponent(f)}:b[d]=decodeURIComponent(f))});return b},I=()=>(window.location.hostname||window.origin).endsWith(".dailymotion.com"),ka=(a,b,c,d)=>{a.addEventListener(b,c,d);return()=>
{a.removeEventListener(b,c,d)}},Q=function(a,b){document.cookie=[`${a}=${b}`,"path=/",`max-age=${2<arguments.length&&void 0!==arguments[2]?arguments[2]:31536E6}`,"samesite=lax;secure"].join(";")},R=a=>{const b=window.document.cookie.split(";").map(c=>c.trim()).find(c=>c.startsWith(a));return(null===b||void 0===b?void 0:b.split("=")[1])||""},S=()=>{const a=[],b=new window.Uint16Array(32);window.crypto.getRandomValues(b);b.forEach(c=>a.push(`000${c.toString(16)}`.slice(-4)));return`${a[0]}${a[1]}-${a[2]}-${a[3]}-${a[4]}-${a[5]}${a[6]}${a[7]}`},
y={PUBLIC:{AD_CLICK:"ad_click",AD_COMPANIONSREADY:"ad_companions",AD_DURATIONCHANGE:"ad_durationchange",AD_END:"ad_end",AD_ERROR:"ad_error",AD_IMPRESSION:"ad_impression",AD_LOADED:"ad_loaded",AD_PAUSE:"ad_pause",AD_PLAY:"ad_play",AD_READYTOFETCH:"ad_readytofetch",AD_START:"ad_start",AD_TIMECHANGE:"ad_timeupdate",PLAYER_ASPECTRATIOCHANGE:"pes_aspectratiochange",PLAYER_CRITICALPATHREADY:"playback_ready",PLAYER_END:"end",PLAYER_ERROR:"error",PLAYER_HEAVYADSINTERVENTION:"player_heavyadsintervention",
PLAYER_PIPEXPANDEDCHANGE:"pes_pipexpandedchange",PLAYER_PLAYBACKPERMISSION:"playback_resolution",PLAYER_PLAYBACKSPEEDCHANGE:"playbackspeedchange",PLAYER_PRESENTATIONMODECHANGE:"pes_presentationmodechange",PLAYER_SCALEMODECHANGE:"pes_scalemodechange",PLAYER_START:"start",PLAYER_VIDEOCHANGE:"videochange",PLAYER_VIDEOLISTCHANGE:"videolistchange",PLAYER_VIEWABILITYCHANGE:"pes_viewabilitychange",PLAYER_VOLUMECHANGE:"volumechange",VIDEO_BUFFERING:"waiting",VIDEO_DURATIONCHANGE:"video_durationchange",VIDEO_END:"video_end",
VIDEO_PAUSE:"pause",VIDEO_PLAY:"play",VIDEO_PLAYING:"playing",VIDEO_PROGRESS:"progress",VIDEO_QUALITIESREADY:"qualitiesavailable",VIDEO_QUALITYCHANGE:"qualitychange",VIDEO_SEEKEND:"seeked",VIDEO_SEEKSTART:"seeking",VIDEO_START:"video_start",VIDEO_SUBTITLESCHANGE:"subtitlechange",VIDEO_SUBTITLESREADY:"subtitlesavailable",VIDEO_TIMECHANGE:"timeupdate"},PRIVATE:{ALL:"all",BACK_TO_INLINE_DISPLAY_REQUESTED:"pes_pip_back_to_inline_display_requested",CLOSE_PIP_REQUESTED:"pes_pip_close_requested",COLLAPSE_PIP_REQUESTED:"pes_pip_collapse_requested",
DISPLAY_POSTER_SOONER:"poster_sooner",EXPAND_PIP_REQUESTED:"pes_pip_expand_requested",PLAYER_APIREADY:"apiready",PLAYER_CROSSICONCLICK:"crossiconclick",PLAYER_FULLSCREENCHANGE:"fullscreenchange",PLAYER_NATIVEPIPCHANGE:"presentationmodechange",PLAYER_STATE:"playerstate",WRITE_UID:"pes_write_uid"}},w={CUSTOMCONFIG:"set-ads-config",FULLSCREEN:"fullscreen",INIT_PIP_IFRAME_CHUNK:"initPesPipChunk",LOAD:"load",LOOP:"loop",MUTED:"muted",NOTIFY_EMBEDDER_URL_CHANGED:"notifyEmbedderURLChanged",NOTIFY_PIP_CHANGED:"notifyPesPipChanged",
PAUSE:"pause",PLAY:"play",QUALITY:"quality",PLAYER_VISIBILITY:"notifyPesPlayerVisibility",SCALE:"scaleMode",SEEK:"seek",SPEED:"speed",STATE:"playerstate",SUBTITLES:"subtitle",UPDATE_NEON_TRACKING_DATA:"updateNeonTrackingData",UPDATE_PARAMS:"updatePesParams",VIEWPORT_RESIZE:"notifyPesViewportSizeChanged",VOLUME:"volume",CONTROLS:"controls"},aa=a=>Object.values(y.PUBLIC).includes(a),x=function(a,b){for(var c,d,f=arguments.length,k=Array(2<f?f-2:0),g=2;g<f;g++)k[g-2]=arguments[g];null===(c=a._do_not_use_8d7d83cd2395d780b51b.iframe)||
void 0===c?void 0:null===(d=c.contentWindow)||void 0===d?void 0:d.postMessage(JSON.stringify({command:b,parameters:k}),Y())},O=(a,b)=>{window.postMessage(JSON.stringify({event:a,...b}),window.origin)},J=(a,b,c)=>la(a,b,c),ma=(a,b)=>la(null,a,b),la=(a,b,c)=>ka(window,"message",d=>{let {origin:f,data:k}=d;if((f===window.origin||f===Y())&&k&&"string"===typeof k)try{const g=JSON.parse(k);"all"!==b&&b!==g.event||null!==a&&a._do_not_use_8d7d83cd2395d780b51b.id!==g.id||c(g)}catch(g){}}),T=!1,na=()=>T,Ea=
l().split(",").includes("pes"),q={log:function(a){for(var b=arguments.length,c=Array(1<b?b-1:0),d=1;d<b;d++)c[d-1]=arguments[d];return p(a,"log",...c)},error:function(a){for(var b=arguments.length,c=Array(1<b?b-1:0),d=1;d<b;d++)c[d-1]=arguments[d];return p(a,"error",...c)}},U=!1,oa=new RegExp(/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/),ba=null,Ha=()=>{const a=R("uid_dm");return null===a||void 0===a?void 0:a.match(oa)},Ia=()=>{var a;!1!==(null===(a=u.player)||void 0===a?void 0:
a.hasAds)&&(a=R("uid_dm"),ba=(null===a||void 0===a?0:a.match(oa))?a:S())},Ja=new RegExp(/[A-F0-9]{32}/),M=null,Ka=()=>{const a=U,b=R("v1st_dm");a?(q.log("Config","Got v1st from backend, 3rd party cookie allowed"),M=u.v1st):(null===b||void 0===b?0:b.match(Ja))?(q.log("Config",'Got v1st from 1st party cookie "v1st_dm"'),M=b):(q.log("Config",'Got v1st from backend, v1st_dm created because 3rd party cookie not allowed and 1st party cookie "v1st_dm" does not exist'),M=u.v1st,na&&Q("v1st_dm",M,604800))},
La="xbzwps xbzwyj xkb83k x5xhrd x2k4l07 xgphb5 x2k4kr6 x2k4l64 x1fv3qc x1uzrwn".split(" "),pa={inherit:"","16:9":"56.25%","4:3":"75%","1:1":"100%","3:4":"133.3%","9:16":"177.7%"},qa={SMALL:480,MEDIUM:1800,LARGE:2160},Ma="fit fill fillLeft fillRight fillTop fillBottom".split(" "),ca=function(a,b){let c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{};const d=Object.prototype.hasOwnProperty.call(pa,b)?b:"16:9",{id:f,iframe:k,rootNode:g,stateFromPES:r}=a._do_not_use_8d7d83cd2395d780b51b;Object.assign(g.style,
{background:"#0d0d0d",height:"inherit"===d?"100%":"",paddingBottom:pa[d],position:"relative",width:"inherit"===d?"100%":""});Object.assign(k,{height:"100%",width:"100%"});r.playerAspectRatio=d;c.withPesEvent&&O(y.PUBLIC.PLAYER_ASPECTRATIOCHANGE,{id:f,aspectRatio:d})},da=function(a,b){let c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{};const d=Ma.includes(b)?b:"fit",{id:f,stateFromPES:k}=a._do_not_use_8d7d83cd2395d780b51b;k.playerScaleMode=d;c.withPesEvent&&O(y.PUBLIC.PLAYER_SCALEMODECHANGE,
{id:f,scaleMode:d})},ra=()=>{const a=window.navigator.connection;return a&&a.effectiveType?a.effectiveType:null},V=a=>{const b={};Object.keys(a).forEach(function(c){const d=a[c];if(void 0!==d&&null!==d&&""!==d){if(null===d)var f=!1;else"object"!==typeof d?f=!1:(f=Object.getPrototypeOf(d),f=f===Object.prototype||null===f);b[c]=f?V(d):d}});return b},Na=()=>{const a=window.performance.getEntriesByType("resource").find(c=>c.name===document.currentScript.src),b=function(c){let d=1<arguments.length&&void 0!==
arguments[1]?arguments[1]:6E3;return"number"!==typeof c||Number.isNaN(c)||0>c?null:c>d?d:Math.round(c)};return a?{pes_res:{start_time:b(a.startTime,3E4)},pes_custom:{script_request:b(a.requestStart-a.startTime),script_response_start:b(a.responseStart-a.startTime),script_response_end:b(a.responseEnd-a.startTime)}}:null},{udger:{browserOsFamily:sa,browserOsName:ta,browserUaFamily:ua,browserUaName:va,browserUaVersion:Oa,deviceType:wa},geoip:{visitorAsNumber:xa,visitorCity:Pa,visitorContinent:ya,visitorCountry:za,
visitorRegion:Aa},player:N,playerEnv:Qa,trafficSegment:ea}=u,Ra=a=>{a={channel:"player",edward:"1.1",sent_ts:Date.now(),events:a.map(V),stack_ctx:{player_stack:"noworker"}};window.fetch("https://pebed.dm-event.net",{method:"POST",body:JSON.stringify(a)})},Ba=async a=>{let {name:b,emptyPlayer:c,pesUUID:d,pesIframeIndex:f,pesIntegrationType:k}=a;if(F("PV5_WATCHTOWER")){a=Date.now();var {pesLastEventTs:g}=window.dailymotion._do_not_use_8d7d83cd2395d780b51b;g={name:b,version:"1.0",data:{browser:{effective_connection_type:ra(),
os_family:sa,os_name:ta,ua_family:ua,ua_name:va,user_agent:window.navigator.userAgent},created_ts:a,device:{type:wa,height:window.screen.height,width:window.screen.width},player:{embedder:document.location.href,embedder_hostname:document.location.hostname,pes_uuid:d,pes_iframe_index:f,pes_integration_type:k,is_empty:c,pubtool:"pes",version:"v-0.0.3507-rc1",settings:Z(N,"isTrackable")},timestamp:{created_event:a,delta_previous_event:g?a-g:0},visitor:{as_number:xa,city:Pa,continent:ya,country:za,id:M,
onsite:I(),referer:document.referer,region:Aa,timezone_offset:-6E4*(new Date).getTimezoneOffset(),traffic_segment:ea}}};N.ownerId&&(g.data.publisher={xid:N.ownerId});window.dailymotion._do_not_use_8d7d83cd2395d780b51b.pesLastEventTs=a;a={channel:"player",edward:"1.1",events:[V(g)],sent_ts:Date.now()};try{const r=await window.fetch("https://pebed.dm-event.net",{method:"POST",body:JSON.stringify(a),headers:{"content-type":"text/plain; charset=UTF-8"}});200===r.status?q.log("Watchtower",b,"sent",a.events[0]):
q.error("Watchtower",b,"failed",r.status,a.events[0])}catch(r){q.error("Watchtower",b,"failed",r.message,a.events[0])}}},Sa={initialize:a=>{const {id:b,observer:c,rootNode:d,settings:f,stateFromPES:k}=a._do_not_use_8d7d83cd2395d780b51b,g={};a._do_not_use_8d7d83cd2395d780b51b.removeAllListeners=J(a,y.PRIVATE.ALL,e=>{let {id:m,event:h,fullscreen:n,mode:z,playerHeavyAdsInterventionReports:C,playerHeavyAdsEvents:H}=e;[y.PRIVATE.PLAYER_FULLSCREENCHANGE,y.PRIVATE.PLAYER_NATIVEPIPCHANGE].includes(h)&&(e=
h===y.PRIVATE.PLAYER_FULLSCREENCHANGE?n?"fullscreen":"inline":"inline"===z?"inline":"nativePip",k.playerPresentationMode=e,O(y.PUBLIC.PLAYER_PRESENTATIONMODECHANGE,{id:m,playerPresentationMode:e}));g[h]&&aa(h)&&(h===y.PUBLIC.PLAYER_HEAVYADSINTERVENTION?(g[h].forEach(B=>{({cb:B}=B);B({playerHeavyAdsInterventionReports:C})}),q.log("Heavy Ads","Received reports",C),0<H.length&&(q.log("Heavy Ads","Received events",H),Ra(H))):a.getState().then(B=>{g[h].slice().forEach(D=>{({cb:D}=D);D(B)})}))});const r=
e=>{const m=J(a,y.PRIVATE.PLAYER_STATE,h=>{Object.assign(h,k);e(h)});x(a,w.STATE);return m};a.pause=()=>x(a,w.PAUSE);a.play=()=>x(a,w.PLAY);a.seek=e=>x(a,w.SEEK,e);a.setMute=e=>x(a,w.MUTED,e);a.setQuality=e=>x(a,w.QUALITY,e);a.setSubtitles=e=>x(a,w.SUBTITLES,e);a.setVolume=e=>x(a,w.VOLUME,e);a.setFullscreen=e=>x(a,w.FULLSCREEN,e);a.setControls=()=>{console.warn("The setControls method has been deprecated. Please check https://developers.dailymotion.com/player/#changelog for more details")};a.setCustomConfig=
e=>{x(a,w.CUSTOMCONFIG,e)};a.setLoop=e=>{x(a,w.LOOP,e)};a.setPlaybackSpeed=e=>{x(a,w.SPEED,e)};a.setAspectRatio=e=>{ca(a,e,{withPesEvent:!0})};a.setScaleMode=e=>{x(a,w.SCALE,e);da(a,e,{withPesEvent:!0})};a.loadContent=e=>{let {video:m,playlist:h,startTime:n}=e;q.log("API","player.loadContent(), with params:",{video:m,playlist:h,startTime:n});e="on"===f.autostart||"firstTimeViewable"===f.autostart&&c.wasViewableAtLeastOnce;if(I()){const z=window.location.href;q.log("API","sendCommandToPlayer(COMMANDS.NOTIFY_EMBEDDER_URL_CHANGED), with url:",
z);x(a,w.NOTIFY_EMBEDDER_URL_CHANGED,z)}x(a,w.LOAD,m,{playlist:h,start:n,autoplay:e})};a.updateParams=e=>{void 0!==e.enableControls&&console.warn("The enableControls parameter from updateParams method has been deprecated. Please check https://developers.dailymotion.com/player/#changelog for more details");void 0!==e.aspectRatio&&ca(a,e.aspectRatio,{withPesEvent:!0});void 0!==e.scaleMode&&da(a,e.scaleMode,{withPesEvent:!0});x(a,w.UPDATE_PARAMS,e)};a.on=function(e,m){let {once:h=!1}=2<arguments.length&&
void 0!==arguments[2]?arguments[2]:{};if(void 0!==e)if("string"===typeof e&&aa(e))if("function"!==typeof m)console.warn(`The specified callback should be a function, received ${m}`);else if(g[e]||(g[e]=[]),g[e].find(C=>{({originalCb:C}=C);return C===m}))console.warn(`Callback duplication detected for ${e}`);else{var n=m;h&&(m=function(){z();n(...arguments)});var z=()=>{g[e]&&(g[e]=g[e].filter(C=>C.originalCb!==n))};g[e].push({originalCb:n,cb:m});return z}else console.warn(`Unknown event, received ${e}`)};
a.off=(e,m)=>{void 0!==e&&("string"===typeof e&&aa(e)?g[e]?void 0===m?delete g[e]:"function"!==typeof m?console.warn(`The specified callback should be a function, received ${m}`):g[e]=g[e].filter(h=>h.originalCb!==m):console.warn(`No listener on ${e} to remove`):console.warn(`Unknown event, received ${e}`))};a.getState=()=>new Promise((e,m)=>{const h=J(a,y.PUBLIC.PLAYER_HEAVYADSINTERVENTION,()=>{n();h();m();console.warn(`player.getState() rejected : player ${b} has been destroyed by Heavy Ads`)}),
n=r(z=>{n();h();e(z)})});a.getRootNode=()=>d;a.getSettings=()=>Z(f,"isPublic");I()&&(a.setControlsForNeon=e=>{x(a,w.CONTROLS,e)})}},fa=!1;class Ta{constructor(a){let {embedIndex:b,emptyPlayer:c,iframe:d,iframeId:f,observer:k,placeholderNode:g,rootNode:r,settings:e,spinner:m}=a;a=window.innerWidth<=qa.SMALL?"smallViewport":"largeViewport";let h="off"===e.pip?"disabled":"enabled";this.hasReceivedVideoChange=this.isEmpty=this.apiReadyReceived=!1;this._do_not_use_8d7d83cd2395d780b51b={id:f,iframe:d,index:b,
initialized:!1,observer:k,placeholderNode:g,rootNode:r,settings:e,spinner:m,stateFromPES:{playerAspectRatio:null,playerIsViewable:null,playerPip:null,playerPipDisplay:a,playerPipIsExpanded:!1,playerPipStatus:h,playerPresentationMode:"inline",playerScaleMode:null},viewportResizeListener:null};k.init(d);this.isEmpty=c;ca(this,e.aspectRatio);da(this,e.scaleMode);if(!Ha()){let n=J(this,y.PRIVATE.WRITE_UID,()=>{var z;!1!==(null===(z=u.player)||void 0===z?void 0:z.hasAds)&&na&&Q("uid_dm",ba,33696E3);n()})
}this.apiReadyReceived=new Promise(n=>{let z=J(this,y.PRIVATE.PLAYER_APIREADY,()=>{d.removeAttribute("name");m&&(d.style.opacity=1,m.remove());z();n()})});if(F("PV5_DISPLAY_POSTER_SOONER")){let n=J(this,y.PRIVATE.DISPLAY_POSTER_SOONER,()=>{d.style.opacity=1;m.remove();n()})}Sa.initialize(this);"off"===e.pip?fa=Promise.resolve():(window.dailymotion._do_not_use_8d7d83cd2395d780b51b.playerSelectedForPip?console.warn(`[${e.id}] ${"PIP is already enabled with another configuration"}`):window.dailymotion._do_not_use_8d7d83cd2395d780b51b.playerSelectedForPip=
this,fa=window._dmDynamicImportPolyfill("pes.pip.eb614922.js"))}initialize(){let {initialized:a}=this._do_not_use_8d7d83cd2395d780b51b;if(a)return a;let {settings:{autostart:b,pip:c},id:d,iframe:f,observer:k,rootNode:g}=this._do_not_use_8d7d83cd2395d780b51b;k.earlyObserve(g);a=(async()=>{await Promise.all([fa,this.apiReadyReceived]);k.unobserve(g);J(this,y.PUBLIC.PLAYER_VIDEOCHANGE,r=>{({title:r}=r);f.setAttribute("title",`Dailymotion video player - ${r.replaceAll("&","&amp;").replaceAll('"',"&quot;")}`);
this.isEmpty&&!this.hasReceivedVideoChange&&(k.unobserve(g),k.observe(g));this.hasReceivedVideoChange=!0});"off"!==c&&(window.dailymotion._do_not_use_8d7d83cd2395d780b51b.playerSelectedForPip===this&&window.dailymotion.pipResume(),x(this,w.INIT_PIP_IFRAME_CHUNK));Ua();"firstTimeViewable"===b&&Va(this);Wa(this);q.log("Player",`${d} fully initialized`);k.observe(g);return this})();return this._do_not_use_8d7d83cd2395d780b51b.initialized=a}destroy(){let {id:a,observer:b,placeholderNode:c,removeAllListeners:d,
rootNode:f,viewportResizeListener:k}=this._do_not_use_8d7d83cd2395d780b51b;b.unobserve(f);d();Xa(this);f.parentNode.replaceChild(c,f);this===window.dailymotion._do_not_use_8d7d83cd2395d780b51b.playerSelectedForPip&&(window.dailymotion.pipClose(),window.dailymotion._do_not_use_8d7d83cd2395d780b51b.playerSelectedForPip=null);window.removeEventListener("resize",k);delete window.dailymotion._do_not_use_8d7d83cd2395d780b51b.players[a]}isEligibleForPipDisplay(a){let {settings:{pip:b}}=this._do_not_use_8d7d83cd2395d780b51b;
return"off"===b?{status:!1,reason:"PIP is OFF"}:this.isEmpty&&!this.hasReceivedVideoChange?{status:!1,reason:"empty embed without videochange event"}:a?{status:!0,reason:"PIP is ON and was viewable at least once"}:{status:"instant"===b,reason:"instant"===b?"PIP is INSTANT":"was not viewable at least once"}}}let Va=a=>{const b=J(a,y.PUBLIC.PLAYER_VIEWABILITYCHANGE,c=>{let {viewable:d,wasViewableAtLeastOnce:f}=c;a&&(d||a.isEligibleForPipDisplay(f).status)&&(b(),a.play())})},Wa=a=>{a._do_not_use_8d7d83cd2395d780b51b.viewportResizeListener=
()=>{x(a,w.VIEWPORT_RESIZE,{width:window.innerWidth,height:window.innerHeight})};window.addEventListener("resize",a._do_not_use_8d7d83cd2395d780b51b.viewportResizeListener)},Ua=()=>{ma(y.PUBLIC.PLAYER_VIEWABILITYCHANGE,a=>{let {viewable:b,id:c}=a;if(a=window.dailymotion._do_not_use_8d7d83cd2395d780b51b.players[c])a._do_not_use_8d7d83cd2395d780b51b.stateFromPES.playerIsViewable=b,x(a,w.PLAYER_VISIBILITY,b)})},Xa=a=>{const b=c=>{console.warn(`Invalid call to player.${c}() : player ${a._do_not_use_8d7d83cd2395d780b51b.id} has been destroyed`)};
Object.keys(a).forEach(c=>{"function"===typeof a[c]&&(a[c]=()=>{b(c)})});Object.getOwnPropertyNames(Object.getPrototypeOf(a)).forEach(c=>{"constructor"!==c&&"function"===typeof a[c]&&(a[c]=()=>{b(c)})})},Ca=[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1],Za=(a,b,c,d)=>{if(!0===b)return q.log("Observer","No header overlapping ! Reason: IO isVisible is true"),{status:!1,marginTop:null};const {x:f,y:k,width:g,height:r}=a.getBoundingClientRect();if(0<=k)return q.log("Observer",`Overlapping detection canceled ! Reason : Player is not about to pass above the fold, y:${k}`),
{status:!1,marginTop:null};a=document.elementFromPoint(f+Math.round(.5*g),k+Math.round(r*(1-d)));if(!a)return q.log("Observer","No header overlapping ! Reason: No overlapping element"),{status:!1,marginTop:null};if(c.isSameNode(a))return q.log("Observer","No header overlapping ! Reason: Overlapping element is the same as the player iframe"),{status:!1,marginTop:null};c=Ya(a);if(!c)return q.log("Observer",'No header overlapping ! Reason: Overlapping element or ancestors are not in "fixed" position'),
{status:!1,marginTop:null};const {x:e,y:m,width:h,height:n}=c.getBoundingClientRect();q.log("Observer",`Overlapping header detection data :
        - IO isVisible : ${b}
        - targetX : ${f}
        - targetY : ${k}
        - targetWidth : ${g}
        - targetHeight : ${r}
        - fixedElementX : ${e}
        - fixedElementY: ${m}
        - fixedElementWidth: ${h}
        - fixedElementHeight: ${n}
        - fixed element:`,c,"\n        - overlapping element:",a);if(0!==m)return q.log("Observer","No header overlapping ! Reason: Overlapping element Y position is not 0"),{status:!1,marginTop:null};if(!(e<=f&&h>=g))return q.log("Observer","No header overlapping ! Reason: Overlapping element is not fully covering the player width"),{status:!1,marginTop:null};q.log("Observer","Fixed header is overlapping player iframe");return{status:!0,marginTop:n}},Ya=a=>{try{for(;a;){const b=window.getComputedStyle(a).getPropertyValue("position").toLowerCase();
if("fixed"===b||"sticky"===b)return a;a=a.parentNode instanceof HTMLElement&&"BODY"!==a.tagName?a.parentNode:null}return null}catch(b){return null}};class $a{constructor(){this.uiActionOrigin=this.intersectionObserver=null;this.earlyObserverMode=this.wasViewableAtLeastOnce=!1;this.playerIframe=null;this.hasCompletedHeaderDetection=!1;this.intersectionObserver=new window.IntersectionObserver(this.intersectionObserverCallback.bind(this),{threshold:Ca})}init(a){this.playerIframe=a;q.log("Observer","Observer initialized with header detection")}intersectionObserverCallback(a){a.forEach(b=>
{let {intersectionRatio:c,target:d,isVisible:f}=b;if((b=.5<=c)&&!this.hasCompletedHeaderDetection&&0>=d.getBoundingClientRect().y){let {status:k,marginTop:g}=Za(d,f,this.playerIframe,.5);k&&(this.hasCompletedHeaderDetection=!0,b=!1,this.intersectionObserver.disconnect(),this.intersectionObserver=null,q.log("Observer","Defining new observer with root marginTop",g),this.intersectionObserver=new window.IntersectionObserver(this.intersectionObserverCallback.bind(this),{rootMargin:`-${g}px 0px 0px 0px`,
threshold:Ca}),this.intersectionObserver.observe(d))}b&&!this.wasViewableAtLeastOnce&&(q.log("Observer","Player iframe was viewable at least once"),this.wasViewableAtLeastOnce=!0);this.earlyObserverMode||O(y.PUBLIC.PLAYER_VIEWABILITYCHANGE,{id:d.id,viewable:b,wasViewableAtLeastOnce:this.wasViewableAtLeastOnce,...(this.uiActionOrigin?{uiActionOrigin:this.uiActionOrigin}:{})});this.uiActionOrigin=null})}observe(a){var b;null===(b=this.intersectionObserver)||void 0===b?void 0:b.observe(a)}earlyObserve(a){var b;
q.log("Observer","Early intersection observer has started");this.earlyObserverMode=!0;null===(b=this.intersectionObserver)||void 0===b?void 0:b.observe(a)}unobserve(a){var b;this.earlyObserverMode=!1;null===(b=this.intersectionObserver)||void 0===b?void 0:b.unobserve(a)}disconnect(){var a;null===(a=this.intersectionObserver)||void 0===a?void 0:a.disconnect()}setUIActionOrigin(a){this.uiActionOrigin=a}}let Da={create:async function(a,b,c,d){let {videoId:f,playlistId:k,playerId:g,params:r,settings:e,
referrerPolicy:m}=4<arguments.length&&void 0!==arguments[4]?arguments[4]:{};if(document.body&&document.body.contains(a)){var h=a.id||`dailymotion-instance-${S()}`,n=a.parentNode,z=window.dailymotion._do_not_use_8d7d83cd2395d780b51b.iframeIndex++,C=!f&&!k,H=new $a,B=ja(r),D=ja(e),ha=`pes${(null===B||void 0===B?0:B.dmPubtool)?`-${B.dmPubtool}`:""}`,E=window.dailymotion._do_not_use_8d7d83cd2395d780b51b.settings,A=E[g];if(void 0===A)try{var G=`${ia()}/player/${g}.json`;F("PV5_USE_GEO2_IFRAME")&&F("PV5_USE_GEO2_UDGER_HEADERS")&&
(G=`${G}?dmEnableUdgerHeaders=true`);A=await (await window.fetch(G,{method:"GET"})).json();q.log("Player settings",A);"server_error"===A.status&&console.warn(`${"An unexpected error occured when retrieving player configuration"} : ${A.id}`);"not_found"===A.status&&console.warn(`${"The player configuration ID has not been found"} : ${A.id}`);"deleted"===A.status&&console.warn(`${"The player configuration ID has been deleted"} : ${A.id}`);E[A.id]=A}catch(ab){console.error("Settings fetch error: ",ab);
return}A=Fa(A,D);B=bb(f,k,g,B,m);E=document.createElement("div");E.id=h;E.classList.add("dailymotion-player-root");E.classList.add(`dailymotion-player-${g}`);D=document.createElement("div");D.className="dailymotion-player-wrapper";Object.assign(D.style,{height:"100%",overflow:"hidden",position:"absolute",width:"100%",margin:"0.00001px"});var K;G=document.createElement("div");var W=640<((null===n||void 0===n?void 0:null===(K=n.getBoundingClientRect())||void 0===K?void 0:K.width)||0)?"48":"40";Object.assign(G.style,
{height:`${W}px`,left:"50%",position:"absolute",top:"50%",transform:"translate3d(-50%, -50%, 0)",width:`${W}px`});G.innerHTML=`<svg
      xmlns="http://www.w3.org/2000/svg"
      height="${W}"
      viewBox="0 0 50 50"
      width="${W}"
    >
      <circle
        cx="25"
        cy="25"
        fill="none"
        r="20"
        stroke="#fff"
        stroke-dasharray="125.6, 125.6"
        stroke-width="4"
        transform="rotate(-90 25 25)"
      />
    </svg>`;G.querySelector("circle").animate([{strokeDashoffset:"125.6"},{strokeDashoffset:"0"},{strokeDashoffset:"-125.6"}],{duration:1200,iterations:Infinity});H=new Ta({embedIndex:b,emptyPlayer:C,iframe:B,iframeId:h,observer:H,placeholderNode:a,rootNode:E,settings:A,spinner:G});window.dailymotion._do_not_use_8d7d83cd2395d780b51b.players[h]=H;D.appendChild(G);E.appendChild(D);n.replaceChild(E,a);h=await cb({embedIndex:b,iframeId:h,pesIframeIndex:z,pesIntegrationType:d,pesUUID:c,pubtool:ha,settings:A});
B.name=encodeURIComponent(h);D.appendChild(B);Ba({name:"vital_pes_iframe_start",emptyPlayer:C,pesIframeIndex:z,pesIntegrationType:d,pesUUID:c});return H}console.warn("The player placeholder node must be added in the body element")}},bb=function(a,b,c){let d=3<arguments.length&&void 0!==arguments[3]?arguments[3]:{},f=4<arguments.length?arguments[4]:void 0;const k=document.createElement("iframe"),g="default"!==c?`/player/${c}.html`:"/player.html",r={...(a&&{video:a}),...(b&&{playlist:b})};Object.keys(d).filter(h=>
!r[h]).forEach(h=>{d[h]&&"object"===typeof d[h]?Object.keys(d[h]).forEach(n=>{r[`${h}[${n}]`]=encodeURIComponent(d[h][n])}):r[h]=encodeURIComponent(d[h])});var e=window.location.href.match(/dmDevBackendEnv=[-_a-zA-Z0-9]+/);null!==e&&([,e]=e[0].split("="),r.dmDevBackendEnv=e);F("PV5_USE_GEO2_IFRAME")&&F("PV5_USE_GEO2_UDGER_HEADERS")&&(r.dmEnableUdgerHeaders="true");e=Object.keys(r).map(h=>`${h}=${r[h]}`).join("&");const m=["autoplay","fullscreen","picture-in-picture",...(window.navigator.canShare?
["web-share"]:[])];Object.assign(k,{allow:m.join("; "),className:"dailymotion-player",frameBorder:0,src:`${Y()}${g}?${e}`,title:"Dailymotion video player",...(f&&{referrerPolicy:f})});k.style.opacity=0;return k},cb=async a=>{let {embedIndex:b,iframeId:c,pesIframeIndex:d,pesIntegrationType:f,pesUUID:k,pubtool:g,settings:r}=a;const {trafficSegment:e,playerGatekeepers:m,player:h}=u,{location:n,origin:z,innerWidth:C,innerHeight:H}=window,{pesLastEventTs:B,neonTrackingData:D}=window.dailymotion._do_not_use_8d7d83cd2395d780b51b;
a={width:C,height:H};const ha=r.hasOverride?r:void 0;let E=null;if(r.enableReceiveUrlLocation||r.enableSharingUrlLocation)E=n.hostname?n.href:n.ancestorOrigins[0];let A=null;try{A=(new URL(document.referrer)).origin}catch(K){}const [G]=await Promise.all([(async()=>{if(!La.includes(null===h||void 0===h?void 0:h.ownerId))return Promise.resolve(null);try{await window._dmDynamicImportPolyfill("pes.liveramp.25927c16.js");const K=await window.dailymotion._do_not_use_8d7d83cd2395d780b51b.getLiverampEnvelope();
return Promise.resolve(K)}catch(K){return Promise.reject(K)}})(),t()]);Q("_TEST_","1");T="1"===R("_TEST_");Q("_TEST_",null,0);I()?U=T:"undefined"!==typeof window.dmCookie3rdPartyAllowed&&(U=window.dmCookie3rdPartyAllowed,delete window.dmCookie3rdPartyAllowed);Ka();Ia();return JSON.stringify({dmInternalData:{cookies1stPartyAvailable:T,cookies3rdPartyAvailable:U,embedder:E,embedIndex:b,forcedSettings:ha,gatekeepers:m,iframeId:c,initialViewportSize:a,liverampEnvelope:G,logger:l(),neonTrackingData:D,
pesIframeIndex:d,pesIntegrationType:f,pesLastEventTs:B,pesPlayerVersion:"v-0.0.3507-rc1",pesUUID:k,pubtool:g,referer:A,targetOrigin:z,ts:e,uid:ba,v1st:M}})},P=()=>{console.warn("PIP is disabled in the configuration")},db=a=>{q.log("API","dailymotion.forwardNeonTrackingData(data), with data:",a);const {players:b}=window.dailymotion._do_not_use_8d7d83cd2395d780b51b,c=Object.keys(b);0===c.length?window.dailymotion._do_not_use_8d7d83cd2395d780b51b.neonTrackingData=a:x(b[c[0]],w.UPDATE_NEON_TRACKING_DATA,
a)},eb=()=>{const {udger:{browserOsFamily:a,browserOsName:b,browserUaFamily:c,browserUaName:d,browserUaVersion:f}={}}=u;return{osFamily:a,osName:b,uaFamily:c,uaName:d,uaVersion:f}},fb={createPlayer:async function(a){let b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};const {settings:c,embedScriptIndex:d,pesUUID:f}=window.dailymotion._do_not_use_8d7d83cd2395d780b51b,k=document.querySelector(`#${a}`);if(!k)return Promise.reject(Error(`${"DOM element ID not found"} : #${a}`));if(k.classList.contains("dailymotion-player-wrapper"))return Promise.reject(Error(`${"A player instance is already attached to this DOM element"} : #${a}`));
if(b&&"object"!==typeof b)return Promise.reject(Error("Player options invalid, please use an object"));b.player||(1===Object.keys(c).length?b.player=Object.keys(c)[0]:(1<Object.keys(c).length&&console.warn("Several player configurations are imported, please specify a player configuration ID"),b.player="default"));return(await Da.create(k,d,f,"lib",{videoId:b.video,playlistId:b.playlist,playerId:b.player,params:b.params,settings:b.settings,referrerPolicy:b.referrerPolicy})).initialize()},events:y.PUBLIC,
getAllPlayers:()=>{const {players:a}=window.dailymotion._do_not_use_8d7d83cd2395d780b51b,b=[];if(0===Object.keys(a).length)return Error("No player found in the page");Object.values(a).forEach(c=>b.push(c.initialize()));return b},getPlayer:a=>{const {players:b}=window.dailymotion._do_not_use_8d7d83cd2395d780b51b,c=b[a];return 0===Object.keys(b).length?Promise.reject(Error("No player found in the page")):void 0===a?1<Object.keys(b).length?Promise.reject(Error("There are multiple players in the page, please specify an ID")):
Object.values(b)[0].initialize():void 0===c?Promise.reject(Error(`${"Player ID not found"} : #${a}`)):c.initialize()},pipClose:P,pipCollapse:P,pipExpand:P,pipRepaint:P,pipResume:P,...(I()&&{forwardNeonTrackingData:db,getEnvironmentInfo:eb}),_do_not_use_8d7d83cd2395d780b51b:{api:null,embedScriptIndex:1,iframeIndex:1,neonTrackingData:null,pesUUID:null,players:{},playerSelectedForPip:null,screenId:S(),settings:{}}};window._dmDynamicImportPolyfill=a=>{const b=`pes-${a}`;var c=document.querySelector(`script[id="${b}"]`);
if(c)return v(c);c=document.createElement("script");c.src=`${"https://static1.dmcdn.net/playerv5"}/${a}`;c.id=b;a=v(c);document.body.appendChild(c);return a};let X=u.player;if(!X)throw Error("Backend settings not set");let {id:gb,status:hb}=X;(async()=>{var a;let b=document.currentScript,{dataset:{video:c,playlist:d,params:f,settings:k},referrerPolicy:g,src:r}=b;var e=!c&&!d;let m=r.match(/\/libs\//)?"lib":"embed",h=!!r.match(/geo2/)||!1,n=S();null!==(a=window.dailymotion)&&void 0!==a&&a.createPlayer||
(window.dailymotion={...window.dailymotion,...fb});Ba({name:"vital_pes_enter",emptyPlayer:"lib"===m?null:e,pesIntegrationType:m,pesUUID:n});window.dailymotion._do_not_use_8d7d83cd2395d780b51b.pesUUID=n;window.dailymotion._do_not_use_8d7d83cd2395d780b51b.isGeo2=h;q.log("PES UUID",n);"ok"===hb&&(window.dailymotion._do_not_use_8d7d83cd2395d780b51b.settings[X.id]=X);"function"===typeof window.dailymotion.onScriptLoaded&&(window.dailymotion.onScriptLoaded(),delete window.dailymotion.onScriptLoaded);"lib"===
m?q.log("Library script loaded"):(a=window.dailymotion._do_not_use_8d7d83cd2395d780b51b.embedScriptIndex++,q.log("Embed script loaded",`Index ${a}`),e={name:"life_cycle.embedStart",version:"1.0",data:{context:{visitor_group:Math.ceil(ea/1E4)},created_ts:Date.now(),empty_player:e,info:{browser:{effective_connection_type:ra(),os_family:sa,os_name:ta,ua_family:ua,ua_name:va,ua_version:Oa,user_agent:window.navigator.userAgent},device:{type:wa,width:window.innerWidth,height:window.innerHeight},player:{config:Z(N,
"isTrackable"),embedder:document.location.href,embedder_hostname:document.location.hostname,env:Qa,is_geo:!0,is_geo2:h,secure:!0,version:"v-0.0.3507-rc1"},visitor:{as_number:xa,continent:ya,country:za,onsite:I(),referer:document.referer,region:Aa,timezone_offset:-6E4*(new Date).getTimezoneOffset(),traffic_segment:ea}},perf:Na(),settings:{embed_index:a,pubtool:"pes"}}},N.ownerId&&(e.data.info.publisher={type:"player",xid:N.ownerId}),e={channel:"player",edward:"1.1",sent_ts:Date.now(),events:[V(e)],
stack_ctx:{player_stack:"noworker"}},window.fetch("https://pebed.dm-event.net",{method:"POST",body:JSON.stringify(e)}),(await Da.create(b,a,n,"embed",{videoId:c,playlistId:d,playerId:gb,params:f,settings:k,referrerPolicy:g})).initialize())})();return{B:qa,C:w,E:300,a:y,b:ka,c:x,d:ma,l:q,s:O}}()
// pv5template